# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.5

# Site settings
title:              New blog
logo:               # Logo image URL
description:        Thoughts, stories and ideas on all things science
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://nubia-jekyll.netlify.com/' # The base hostname & protocol for your site
twitter:            https://twitter.com/aspirethemes
facebook:           https://www.facebook.com/aspirethemes
instagram:          https://www.instagram.com/aspirethemes

markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty


# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ali:
    name:     Alicia Molinero Perez
    bio:      bio here
    gravatar: https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    linkedin: 
    instagram: 
    twitter:  
  bela:
    name:     Bela Sibuet Ruiz
    bio:      bio here
    gravatar: https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    linkedin: 
    instagram: 
    twitter:  
  xenia:
    name:     Xenia Perez Sitja
    bio:      bio here
    gravatar: https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    linkedin: https://www.linkedin.com/in/xeniaps/
    github:   https://github.com/sitjart
    twitter:  https://twitter.com/PerezSitja
  

