# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.5

# Site settings
title:              The Modern Hypatia
logo:               # Logo image URL
description:        Thoughts, stories and ideas on all things science
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://nubia-jekyll.netlify.com/' # The base hostname & protocol for your site
twitter:            https://twitter.com/aspirethemes
facebook:           https://www.facebook.com/aspirethemes
instagram:          https://www.instagram.com/aspirethemes

markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Authors
authors:
  xenia:
    name:     Xènia Pérez Sitjà
    bio:      
    gravatar: https://s.gravatar.com/avatar/7e8f05d96f87d0a80066a2590425688a
    email:    
    website:  
    github:   https://github.com/sitjart
    twitter:  https://twitter.com/PerezSitja
    linkedin: https://www.linkedin.com/in/xeniaps/
  bela:
    name:     Bela Sibuet Ruiz
    bio:      
    gravatar: https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    email:    info@aspirethemes.com
    website:  http://aspirethemes.com
    github:   https://github.com/aspirethemes
    twitter:  https://twitter.com/aspirethemes
  alicia:
    name:     Alicia Molinero Pérez
    bio:      
    gravatar: https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    email:    info@aspirethemes.com
    website:  http://aspirethemes.com
    github:   https://github.com/aspirethemes
    twitter:  https://twitter.com/aspirethemes

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: 'collection/_authors'
      type: authors
    values:
      permalink: "/authors/:title/"
      layout: author
      linkedin: 
  - scope:
      path: '_posts'
      type: posts
    values:
      permalink: "/:title/"
      layout: post
      author: 
      tags:
      image:

